# -*- coding: utf-8 -*-
"""Caddyfile generation.

Only enabled services get a route. A disabled service is therefore invisible
from the outside: there is nothing to probe and nothing to fail.

Every MCP route points at the inspector, not at the MCP process, which is how
the panel can show per-tool telemetry without patching the MCP servers.
"""

from . import config
from .processes import IS_WINDOWS

HEADER = """# Generated by MCP Hub - do not edit by hand.
# Regenerate from the panel (Settings -> Apply) or `python run.py --render`.
"""


def render(cfg=None):
    cfg = cfg or config.load()
    domain = (cfg.get("domain") or "localhost").strip()
    https_port = int(cfg.get("httpsPort") or 8443)
    admin_port = int(cfg.get("adminPort") or 8765)
    inspector_port = int(cfg.get("inspectorPort") or 8770)
    bind = (cfg.get("bind") or "").strip()
    token = cfg.get("token") or ""
    local_only = domain in ("localhost", "127.0.0.1", "")

    out = [HEADER, "{"]
    if local_only:
        # Plain HTTP on a custom port: it must be declared as the HTTP port, not
        # as https_port, and `auto_https` may appear only once - two auto_https
        # lines in one block make Caddy refuse to start with
        # "duplicate global option", so nothing ever listens.
        out.append("\thttp_port %d" % https_port)
        out.append("\tauto_https off")
    else:
        out.append("\thttps_port %d" % https_port)
        out.append("\tauto_https disable_redirects")
    # `caddy reload` speaks to the admin API. With `admin off` every reload
    # fails, the process has to be killed instead, and live sessions die.
    out.append("\tadmin localhost:%d" % int(cfg.get("caddyAdminPort") or 2019))
    if cfg.get("email"):
        out.append("\temail %s" % cfg["email"])
    out.append("}")
    out.append("")

    site = ("http://localhost:%d" % https_port) if local_only else domain
    if bind:
        out.append("%s {" % site)
        out.append("\tbind %s" % bind)
    else:
        out.append("%s {" % site)

    if not local_only and https_port == 443:
        # Standard port: Caddy picks the challenge itself. HTTP-01 on :80 and
        # TLS-ALPN on :443 both work, so the certificate is issued and renewed
        # automatically with no extra configuration.
        out.append("\t# TLS: automatic Let's Encrypt certificate (HTTP-01 / TLS-ALPN).")
        out.append("")
    elif not local_only:
        # Non-standard port: TLS-ALPN validation can only arrive on 443, so the
        # router must forward 443 -> https_port. Without that forward no
        # certificate is ever issued - the panel now says so explicitly.
        out.append("\t# Requires port forwarding 443 -> %d, else ACME cannot verify."
                   % https_port)
        out.append("\ttls {")
        out.append("\t\tissuer acme {")
        out.append("\t\t\tdisable_http_challenge")
        out.append("\t\t\talt_tlsalpn_port %d" % https_port)
        out.append("\t\t}")
        out.append("\t}")
        out.append("")

    out.append("\tlog {")
    out.append("\t\toutput file %s {" % _caddy_path(config.LOGS / "access.log"))
    out.append("\t\t\troll_size 8mb")
    out.append("\t\t\troll_keep 3")
    out.append("\t\t}")
    out.append("\t}")
    out.append("")

    out.append("\t# Liveness probe - always open, never leaks anything.")
    out.append("\thandle /healthz {")
    out.append("\t\trespond \"ok\" 200")
    out.append("\t}")
    out.append("")
    out.append("\t# OAuth discovery, Dynamic Client Registration and PKCE endpoints.")
    for oauth_path in ("/.well-known/oauth-protected-resource*",
                       "/.well-known/oauth-authorization-server*",
                       "/.well-known/openid-configuration*", "/oauth/*"):
        out.append("\thandle %s {" % oauth_path)
        out.append("\t\treverse_proxy 127.0.0.1:%d" % admin_port)
        out.append("\t}")
    out.append("")
    out.append("\t# Control panel.")
    out.append("\thandle /admin* {")
    out.append("\t\treverse_proxy 127.0.0.1:%d" % admin_port)
    out.append("\t}")
    out.append("")

    if token and any((svc.get("authMode") or "token") == "token"
                     for svc in config.enabled_services(cfg)):
        # `not` is a matcher token, not a directive: the negation has to live in
        # a named matcher, otherwise Caddy rejects the whole config and keeps
        # serving the previous one (old token -> 401 for clients).
        out.append("\t@unauthorized not header Authorization \"Bearer %s\"" % token)
        out.append("")

    enabled = config.enabled_services(cfg)
    for svc in enabled:
        upstream = config.upstream_of(svc)
        if not upstream:
            continue
        path = svc.get("path") or ("/" + svc["id"])
        auth_mode = svc.get("authMode") or "token"
        out.append("\t# %s -> inspector -> %s (auth: %s)" %
                   (svc.get("label") or svc["id"], upstream, auth_mode))
        out.append("\thandle %s* {" % path)
        if auth_mode == "token" and token:
            out.append("\t\trespond @unauthorized \"unauthorized\" 401")
        elif auth_mode == "oauth":
            out.append("\t\t# OAuth access token is validated by the inspector.")
        out.append("\t\trewrite * /_inspect/%s" % svc["id"])
        out.append("\t\treverse_proxy 127.0.0.1:%d {" % inspector_port)
        out.append("\t\t\tflush_interval -1")   # never buffer: SSE must stream
        out.append("\t\t\ttransport http {")
        out.append("\t\t\t\tversions 1.1")
        out.append("\t\t\t}")
        out.append("\t\t}")
        out.append("\t}")
        out.append("")

    out.append("\t# Nothing else is exposed.")
    out.append("\thandle {")
    out.append("\t\trespond \"not found\" 404")
    out.append("\t}")
    out.append("}")
    out.append("")
    return "\n".join(out)


def _caddy_path(path):
    text = str(path)
    if IS_WINDOWS:
        text = text.replace("\\", "/")
    return "\"%s\"" % text


def path():
    return config.ROOT / "Caddyfile"


def write(cfg=None):
    content = render(cfg)
    target = path()
    if target.exists() and target.read_text(encoding="utf-8") == content:
        return target, False
    target.write_text(content, encoding="utf-8")
    return target, True


def routes(cfg=None):
    """What the outside world can reach right now."""
    cfg = cfg or config.load()
    local_only = (cfg.get("domain") or "localhost") in ("localhost", "127.0.0.1", "")
    base = ("http://localhost:%d" % int(cfg["httpsPort"])) if local_only \
        else "https://%s" % cfg["domain"]
    items = [{"path": "/healthz", "url": base + "/healthz", "auth": False, "kind": "system"},
             {"path": "/admin", "url": base + "/admin/", "auth": False, "kind": "system"}]
    for svc in config.enabled_services(cfg):
        items.append({
            "path": svc.get("path"),
            "url": base + (svc.get("path") or ""),
            "auth": (svc.get("authMode") or "token") != "none",
            "authMode": svc.get("authMode") or "token",
            "kind": "mcp",
            "service": svc["id"],
        })
    return items
